server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html index.htm;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(html|css|js|json|png|jpg|jpeg|gif|ico|svg)$ {
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    expires off;
  }

}
